### ISSUE TITLE
sound and color

### ISSUE THREAD

**Issue by DRagonenko** [Protonerd/FX-SaberOS#1]
https://youtu.be/4xO36PvQsWU
correctly plays audio files . the blade color is not changing =(
Sorry if I have mistakes. I'm not good enough in English

**Comment by jbkuma** [comment]
The color change is the "Gravity color" from LSOS 1.5

Here is a video demonstrating the color:
https://www.youtube.com/watch?v=crkaLPb7E7s

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by DRagonenko** [comment]
sound problems 
Problems with the changing color of the blade
https://youtu.be/3OcxuN5DtIA

**Comment by jbkuma** [comment]
https://youtu.be/3OcxuN5DtIA?t=75

The part that is red is the color to be added or subtracted.  You must turn
your board to different angles to make this bright to add, or dim to
subtract.  I can see when you turn the board the end changes color
correctly.  The button must be pressed when the tip is on the correct color.



Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by DRagonenko** [comment]
does not retain changes
https://youtu.be/tnWBY4ims0E

**Comment by DRagonenko** [comment]
not plays those files
