### ISSUE TITLE
Flame effects

### ISSUE THREAD

**Issue by fadroid** [Protonerd/FX-SaberOS#100]
Hello,
I have been playing around with the flame effect and I can't seem to figure it out. My goal is to keep most of the blade red with only a little bit of the yellow/white flaming up (for the Kylo unstable effect) . I tried changing the numbers on how often it ignites but I don't see a difference. Is what I am asking possible? 

Thanks in advance!

**Comment by jbkuma** [comment]
This is not intended for that sort of effect.

**Comment by fadroid** [comment]
Thanks for the quick response.
