### ISSUE TITLE
button

### ISSUE THREAD

**Issue by DRagonenko** [Protonerd/FX-SaberOS#101]
What needs to be changed in the code to swap the sticking blasters ?

**Comment by Protonerd** [comment]
not sure what you mean. Can you try to explain more in detail?

**Comment by DRagonenko** [comment]
1 pressing clinch
2 pushing blaster
Swap places

**Comment by lemmingDev** [comment]
At about line 40 in Config_HW.h you will see

```//#define SINGLEBUTTON
 
#ifdef DIYINO_PRIME 
  #define MAIN_BUTTON     12
  #ifndef SINGLEBUTTON
    #define AUX_BUTTON   4
  #endif
#else if defined DIYINO_STARDUST_V2 or defined DIYINO_STARDUST_V3
  #define MAIN_BUTTON      12
  #ifndef SINGLEBUTTON
    #define AUX_BUTTON   11 // 2
  #endif
#endif
 ```

Just change the pin numbers around to what you want...
