### ISSUE TITLE
hum loop cut

### ISSUE THREAD

**Issue by JaySlex** [Protonerd/FX-SaberOS#105]
its wierd the looping isnt right, there is a slight cut between the hums.

**Comment by rhansenne** [comment]
Update to v1.6 and the new SD Card image. In the new soundfonts all repeating files have at least a 30s hum baked in, so you can change HUM_RELAUNCH in Config_SW.h to for e.g. 25000 which will basically eliminate hum relaunches unless you keep the saber stationary for long periods of time.
