### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by Himmiko** [Protonerd/FX-SaberOS#19]
I make a lightsaber Arduino+mpu+dfplayer.
I connect according to this scheme.
![homebrew-string](https://user-images.githubusercontent.com/32688939/32851569-558e6bac-ca46-11e7-8136-ed42d54bbd9d.png)
but nothing works.
that's what turns out:
https://youtu.be/KT2rrpyPJqA

What could it be? all set up according to the instructions.

**Comment by faeton13** [comment]
You can uncoment debug functions and check it in arduino through comport
monitor

**Comment by kirkyb** [comment]
It sounds like your sound files haven't been copied over in the right order.

**Comment by Himmiko** [comment]
this is what the port monitor writes

size of StoreStruct: 72
32
L03
EEPROM LOADED
Initializing I2C devices...
Testing device connections...
MPU6050 connection successful
Initializing DMP...
address: 200
output: -3402

address: 202
output: -278

address: 204
output: 940

address: 206
output: 95

address: 208
output: 9

address: 210
output: 4

Enabling DMP...
Enabling interrupt detection (Arduino external interrupt 0)...
DMP ready! Waiting for first interrupt...
Connecting to DFPlayer...
Connected to DFPlayer !

**Comment by Himmiko** [comment]
Sound files are compiled correctly. With the code, JakeSoft works. but there is no Fx.

**Comment by kirkyb** [comment]
To me it sounds like the boot, saber on and saber off sounds aren't right.

**Comment by Himmiko** [comment]
Yes, the sounds are played differently. but the buttons do not respond ..

**Comment by Himmiko** [comment]
Thank you) I figured it all out) reinstalled the program and reinstalled the sounds. Everything is working)

**Comment by kirkyb** [comment]
No problem. Good to hear that you sorted it.

**Comment by Himmiko** [comment]
how can I help the project? for example, can I send money?))

**Comment by kirkyb** [comment]
You could support the developers by purchasing one of the new Stardust boards. Ask Protonerd for more information.

I bought one and it's made making a saber a lot easier. Just make sure that you know exactly what you're doing with it first by thoroughly reading the accompanying manual.

**Comment by raptordemon** [comment]
where are these for sale? i couldn't find a buy link

**Comment by Argathena** [comment]
https://www.fx-sabers.com/forum/index.php?topic=52302.0

**Comment by Himmiko** [comment]
one more question .. what kind of resistors on the battery and button?

**Comment by jbkuma** [comment]
For the LED in the button? You'll have to calculate that based on the
button you have, but if it's a 2v 20ma then a 100ohm would do the job.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by Himmiko** [comment]
Excellent) and on the battery? between A3 and +/-

**Comment by Protonerd** [comment]
If you supply the circuit from a single LiPo/Li-Ion, you do not need any extra connection, the controller will do the job for you. Only if you use a voltage source >5V and connect to VIN or use a DC/DC on 5V you will need a resistor divider to A3.

**Comment by Himmiko** [comment]
I understood everything) thanks)

**Comment by Himmiko** [comment]
Well .. the circuit does not work with 
A3 -> +/- 
rst -> +/-
But with Gnd and without A3, everything works fine)

**Comment by Protonerd** [comment]
Can you make a sketch of your whole wiring?

**Comment by jbkuma** [comment]
If you are using A3 to read the battery you need resistors and indicated to
provide a voltage divider.  Simply connecting the +/- just shorts the
battery...

RST is reset.. there shouldn't be anything connected to this.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by Himmiko** [comment]
jbkuma
> IIf you supply the circuit from a single LiPo/Li-Ion, you do not need any extra connection, the controller will do the job for you. Only if you use a voltage source >5V and connect to VIN or use a DC/DC on 5V you will need a resistor divider to A3.

 connect everything exactly as in this diagram.
![homebrew-pixel](https://user-images.githubusercontent.com/32688939/33089046-83ec49a6-cf00-11e7-89af-e17a00a55711.png)

**Comment by Himmiko** [comment]
except that my battery 18650
