### ISSUE TITLE
sound fonts

### ISSUE THREAD

**Issue by shiryu55** [Protonerd/FX-SaberOS#2]
I would like to understand how to mount the SD with the sound sources for the graflex that are included in the zip, but I do not quite understand how to mount those sound sources.

I decompress the FallenSon file.
In the compressed there are numerous files, ,, in version 1.5 they have a folder structure,
ConfigSounds
Saber_JukeBox
Soundfont1
Soundfont2
Soundfont3
Soundfont4
Soundfont5
Is it supposed to decompress the content of the fallenson into soundfont1? Or be willing to do something else.

A little manual for clumsy would be great.

**Comment by jbkuma** [comment]
These are used like any other font.  It doesn't matter which folder you put
it in as long as your folders are copied to the SD in the correct order.
Just like before your files much match your configuration.



Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe
