### ISSUE TITLE
COLOR_PROFILE

### ISSUE THREAD

**Issue by leofaure** [Protonerd/FX-SaberOS#27]
Hello greetings! Congratulations for the great job.
I am using the latest version of the FX os and have a question about the COLOR_PROFILE.
I activated this function and deactivated the GRAVITY_COLOR.
Where are the 15 colors configured? In the lightsaber the GRAVITY_COLOR continues to work.

my setup is Neopixel homebrew two button.

Thanks for all.may the force be with you!

**Comment by Protonerd** [comment]
Sorry, maybe I was not specific enough in the latest release notes: color profiles will come, but currently what you see is only a place holder.

**Comment by leofaure** [comment]
Ah ok now undestand.thanks for all Proto!
