### ISSUE TITLE
Resistors on A3

### ISSUE THREAD

**Issue by FatherCool** [Protonerd/FX-SaberOS#28]
On the homebrew star. What are the resistors on the nano pin A3 for?

Cheers

**Comment by DRagonenko** [comment]
100 Ком -
470 Ком +

**Comment by FatherCool** [comment]
Yes I know the values I was asking what they did. Cheers.

**Comment by jbkuma** [comment]
It's a voltage divider to read the battery level.

**Comment by FatherCool** [comment]
Ah right so why does it read it and how does it present the info to us? Will the code it work without it?

**Comment by jbkuma** [comment]
There is a battery check function and menu item for battery level. It will
work with out it.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by FatherCool** [comment]
Ah right. Would I need to comment anything out in the code if I didn't fit the resistors?

**Comment by jbkuma** [comment]
You just won't get an accurate reading, you can organize the menu sequence
to move battery check out of use.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by FatherCool** [comment]
I don't need a battery reading so could get rid of it really.
