### ISSUE TITLE
LEDSTRINGS

### ISSUE THREAD

**Issue by DRagonenko** [Protonerd/FX-SaberOS#29]
#define DIYINO_PRIME
LEDSTRINGS 
does not trigger the LEDs

**Comment by Protonerd** [comment]
Do you have an LED string saber at hand? They are quite rare nowadays.

**Comment by DRagonenko** [comment]
cap led 5 mm
version LightSaberOS version 1.5 work
and in the version of  FX-SaberOS not working .

**Comment by Protonerd** [comment]
To be honest since LED string sabers are becoming rare nowadays I haven't checked that particular branch any more. It's not on top of my prio list, but I will sure to have a look in the coming weeks. Is it urgent?

**Comment by DRagonenko** [comment]
no not urgentwait and hope27.12.2017, 17:06, "András Kun" <notifications@github.com>:To be honest since LED string sabers are becoming rare nowadays I haven't checked that particular branch any more. It's not on top of my prio list, but I will sure to have a look in the coming weeks. Is it urgent?

**Comment by DRagonenko** [comment]
no not urgent
wait and hope

**Comment by Protonerd** [comment]
It works perfectly on my side, even wo/any modification.

**Comment by Protonerd** [comment]
Any comment? Otherwise I will close the issue as solved.

**Comment by DRagonenko** [comment]
in some positions not immediately light up but only after hitting
