### ISSUE TITLE
 problems with color on the neopixel

### ISSUE THREAD

**Issue by lJusticel** [Protonerd/FX-SaberOS#43]
Problem when using fxsaberos, the color of the blade does not change the same as on the tip
https://youtu.be/nxUxHd45pIk

**Comment by Protonerd** [comment]
It's a bit hard to see clearly on the vid what is wrong. I see that the tip color is changing, and the blade changes color as well. Actually the blade tip only shows which color you will be able to add or subtract from the current one, i.e. if you have a purple blade (red+blue) and turn the blade to show a dull red at the tip (i.e. subtract red), and keep the button pressed, it will slowly turn the blade color from purple to blue, reducing the drive to the red LED.

**Comment by Protonerd** [comment]
See also : https://github.com/Protonerd/FX-SaberOS/wiki/Gravity-Color

**Comment by lJusticel** [comment]
blue does not turn on in any way, only the tip is glowing

**Comment by Protonerd** [comment]
Try out the new version where you can choose between Gravity Color and Color Profiles. If Color Profiles do not work for you, there is something weird with your stripe.

**Comment by lJusticel** [comment]
the new code works well, thank you
