### ISSUE TITLE
 Creation of a new category in the main menu

### ISSUE THREAD

**Issue by shiryu55** [Protonerd/FX-SaberOS#48]
It would be possible to add some characters in the main menu system.
i mean if i can as example choose vader and this menu, select color . ignition time ,flicker style, etc.. , preconfigured

**Comment by Protonerd** [comment]
Can you describe your idea more clearly?

**Comment by jbkuma** [comment]
I believe what Shiryu would like is to have a preconfigured setup where a
sound profile would match a color profile.  For instance: SF1 InVader red
blade, yellow flash.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by shiryu55** [comment]
correct, jbkmuma, For instance: SF1 InVader red
blade, yellow flash, flicker style, ignition speed, etc.

**Comment by leofaure** [comment]
Greetings kyber masters!, i support this idea and maybe I would add a new ignition option, by wrist twist. Ideal for the saber of Kylo Ren!
Thanks to all those who collaborate in this great operating system. We are a few Spanish speakers following from LSOS.
Soon we will upload photos of how our setups are.
Thanks for all.

**Comment by jbkuma** [comment]
We welcome and encourage customization to see your dreams come true. Please
feel free to join us on Facebook for discussion and to see other projects.

**Comment by MattLeshman** [comment]
I like very much the idea of creating profiles according to characters, linking COLOR with SOUNDFOUNT, and other features for different Characters like Darth Vader, Mace Windu, Luke Skywalker, etc.

**Comment by jbkuma** [comment]
To be clear, if there was pre-set profiles it will never be character
names. We've made an effort to avoid copyright and trademarks. This is why
we changed the name from LSOS.

On Jan 30, 2018 8:28 AM, "MattLeshman" <notifications@github.com> wrote:

I like very much the idea of creating profiles according to characters,
linking COLOR with SOUNDFOUNT, and other features for different Characters
like Darth Vader, Mace Windu, Luke Skywalker, etc.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Protonerd/FX-SaberOS/issues/48#issuecomment-361593127>,
or mute the thread

**Comment by Protonerd** [comment]
Actually what you ask for already exists, each of the sound fonts have their own customizable profile. You can define it and it stays stored in EEPROM. A profile is always described by a sound font and you can assign all the other profile characteristics to it in the config menu.
If you want to have profiles connected to characters, the easiest way is to replace the fontID sound file to announce the characters name. For instance you replace the fontID of bespin2 (a sound font from GCS) to announce Luke Skywalker. Easy as that.

**Comment by MattLeshman** [comment]
Thinking in that way... I think you're totally right!

**Comment by shiryu55** [comment]
Thank you very much for the response, it was unsettling me. Looking at the code, my knowledge of programming is a bit outdated.

**Comment by jbkuma** [comment]
I believe what we are looking for here is the ability to set the colors in
the font profile such as:

    case 0:
      // soundFont directory 01 DARK INVADER:
      this->powerOnTime = 800;
      this->powerOffTime = 800;
      // Blade Color
      this->mainColor.r = 255;
      this->mainColor.g = 0;
      this->mainColor.b = 0;
      this->clashColor.r = 255;
      this->clashColor.g = 255;
      this->clashColor.b = 0;
      this->blasterboltColor.r = 0;
      this->blasterboltColor.g = 255;
      this->blasterboltColor.B = 255;
      break;

note: This doesn't work, it's just an example of how it COULD work.


Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by shiryu55** [comment]
Ok... and could be possible if i can add the fricky style in this profile ??

**Comment by leofaure** [comment]
So, can it be understood by my poor translation into Spanish, each sountfont can have different parameters parameters such as brightness, main color or speed of vision, with different values ​​between sountfontos? In that case, could you show the mechanics to follow?

**Comment by leofaure** [comment]
It occurred to me that it would be an easy way to use an "eco" mode to save energy or simply by being at night or just to testing , or I set a mode maximum brightness to impress your friends...

**Comment by jbkuma** [comment]
At one time I implemented mute more when the hole is powered up while the
activation button is pressed.  I think this could easily be changed to
include a dimmed blade. Search for the quick mute function in the main ino

**Comment by shiryu55** [comment]
could you do me a favour answering the question about leo and me, of being able to put predefined configuration parameters in the sound.h. thanks for all.

***So, can it be understood by my poor translation into Spanish, each sountfont can have different parameters such as brightness, main color or speed of ignition , with different values ​​between sountfontos? In that case, could you show the mechanics of the code to follow? Sorry my english,thanks for all, and good work!

**Comment by jbkuma** [comment]
This feature does not currently exist.  It is something we are considering
for a future release.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by shiryu55** [comment]
ok

**Comment by ec-cts** [comment]
Hi leofaure.:
I am a Spanish speaker like you. I'm starting my lightsaber project, based on arduino nano, mpu6050 and dfplayer mini.
I'm having a hard time understanding the code and I have some doubts.
My main problem is my poor English, and therefore understand the explanations properly.
There is some way to get in touch with you directly or with PM to ask you some questions in Spanish. I Thank you in advance for the help you can give me.

Greetings to all, you do a great job.

Carlos (ec-cts)

**Comment by leofaure** [comment]
Saludos Ec.cts!, te invito a un grupo de telegram que creé hace un tiempo ya, con animo de compartir y colaborar acerca de este gran proyecto creado por grandes y altruistas y genios Protonerd,Jbkuma,y demás colaboradores. Este canal de telegram se creo con la idea de no molestar demasiado al personal de habla inglesa y como canal rápido de comunicación, siéntete libre de saludar y compartir tus dudas e ideas acerca de este proyecto y algunos mas, todos relacionados.

https://t.me/joinchat/AIiqMEKH59010XSDtmAUMQ

Salut!
