### ISSUE TITLE
Blade length 

### ISSUE THREAD

**Issue by Xamiuk** [Protonerd/FX-SaberOS#50]
Hi guys 
A simple question:
How long is your sabers? Because I bought a pixel strip 1 meter and in the meter it has 144 leds but when I check the configuration file the maximum leds are 120 (85cms). It's your blade 85cms long?thank to all the people 

Cheers

**Comment by leofaure** [comment]
...and for the kylo saber would it be necessary to subtract 10 to use those 10 in parallel for the lateral jets?
