### ISSUE TITLE
effects blade intensity

### ISSUE THREAD

**Issue by TedyLupu** [Protonerd/FX-SaberOS#58]
Hello! This is not an issue but a request for help!
I'm using 144leds/m neopixel blade and a CGR18650AF Li-Ion battery. It seems that the power is not enough. Using a 120 leds/side (front & back = total 240 LEDs), when i lightup my saber, i have a 1.8 -> 2A current. The voltage rapidly drops from 4V to under 3.3V (in less then 10 min of usage), point where the electronics stops working. 
I set the max brightness to 120 but this value does not affect the light intensity in effects, like flicker.
How can i set this max_brightness as a global variable to affect all effects on the LEDs?

**Comment by jbkuma** [comment]
The battery is insufficient. You need something that can deliver higher
current like the Orbtronic 10A or TCSS 10A model. Both are protected cells
as well.
