### ISSUE TITLE
colors 

### ISSUE THREAD

**Issue by DRagonenko** [Protonerd/FX-SaberOS#6]
have the ability to disable the gravity of the colors in the new code?

**Comment by Protonerd** [comment]
I will not disable it, as I'm very fond of this method, currently it's the most sophisticated way to change color among all saber boards. But you can disable it by simply omitting the color change items from the config menu by setting them behind CS_LASTMEMBER. If you do so, you must define the color profiles in the code.

**Comment by DRagonenko** [comment]
please make a screenshot where it is in the code.
thank you

**Comment by Protonerd** [comment]
Do you need help here still? Let me know, otherwise close the topic.

**Comment by DRagonenko** [comment]
I do not understand where is the code change.
please make a screenshot

**Comment by Protonerd** [comment]
Have a look at the Wiki: https://github.com/Protonerd/FX-SaberOS/wiki/FlexiConfig
