### ISSUE TITLE
startup

### ISSUE THREAD

**Issue by daky7** [Protonerd/FX-SaberOS#61]
when i give my arduino power saber starts automaticly and plays lockup sound

**Comment by jbkuma** [comment]
It sounds like you have a grounding issue on your activation switch.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by Protonerd** [comment]
Yes, most definitely. Your switch is stuck-on.
