### ISSUE TITLE
Quick Start FXSOS-Saber hardware config

### ISSUE THREAD

**Issue by ec-cts** [Protonerd/FX-SaberOS#63]
**I have two doubts** HOMEBREW STAR-LED

1º)At the time of going to configure the OS in "Config_HW.h", only the Diynos models are indicated but I want to configure them with "homebrew star-led".
You could tell me which option is the equivalent: DIYINO_PRIME or DIYINO_STARDUST.

2º) In the schemes it puts a battery of 2200 ma, but it does not put of what voltage has to be.
I have 18650 batteries of 9800 mh. Can I use them?

**Comment by jbkuma** [comment]
Homebrew should use DIYINO_PRIME.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by ec-cts** [comment]
Trank you

**Comment by ec-cts** [comment]
Can I use a 18650 battery (or two) as a battery?

**Comment by FatherCool** [comment]
Thats what I use for a tri cree.

**Comment by ec-cts** [comment]
Perfect. I use also a tri-cree
