### ISSUE TITLE
Clash not working on stardust v2

### ISSUE THREAD

**Issue by daky7** [Protonerd/FX-SaberOS#67]
Hi, 
I have try everything and I cant get clash sounds to work. Using stock vanilla sounds from FX-saberOS

**Comment by Protonerd** [comment]
It is because of the clash detection setting you inherit probably from the master version. Try in Config_SW.h the following:
//#define CLASH_DET_MPU_INT
#define CLASH_DET_MPU_POLL

and it will work perfectly.
