### ISSUE TITLE
Question about DFPlayer libraries

### ISSUE THREAD

**Issue by DonSaber** [Protonerd/FX-SaberOS#70]
While investigating the compiling error message from previous issue, I noticed something strange about the DFPlayer libraries.

In the folder we have 3 different DFPlayer libraries (DFPlayer, DFPlayer_LSOS, DFPlayer_Mini_Mp3).
In the code we include DFPlayer_Mini_Mp3.h at row 31 of FX-SaberOS.ino.

When compiling, the process is picking the DFPlayerSerial.h from folder DFPlayer_LSOS because the file is missing in folder DFPlayer_Mini_Mp3.

Multiple libraries were found for "DFPlayerSerial.h"
 Used: /Users/smadama/Documents/Arduino/libraries/DFPlayer_LSOS
 Not used: /Users/smadama/Documents/Arduino/libraries/DFPlayer
 Not used: /Users/smadama/Documents/Arduino/libraries/DFPlayer
 Not used: /Users/smadama/Documents/Arduino/libraries/DFPlayer
 Not used: /Users/smadama/Documents/Arduino/libraries/DFPlayer

If I move the DFPlayer folder out of the Libraries folder, the compilation warning disappear, but I guess the file is still picked from DFPlayer_LSOS folder.

Picking the DFPlayerSerial.h file from an alternate folder rather than the one specified in the include command is the expected behaior ?

Just wondering ...

**Comment by Protonerd** [comment]
Would be interesting to know if there are differences at all. But frankly I did not look into this so far. Never change a running machine. As far as I remember the only time I changed that library was when I removed the module reset to eliminate the pop at power up.
