### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by fadroid** [Protonerd/FX-SaberOS#92]
Hello,

A question on button wiring for a homebrew set up with a pixel blade. If I just want a single momentary button without an accent led, is it just ground on one end and d12 on the other? Do I still need to attach anything to A0?

Thanks in advance, this project is some awesome engineering!

**Comment by jbkuma** [comment]
The only thing that gets connected to A0 is an accent LED. It does not need
to be in the switch.  If you are not using an accent LED you do not need to
wire A0 to anything.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by fadroid** [comment]
So to confirm, on d12 is simply a momentary ground signal?

**Comment by jbkuma** [comment]
correct.

**Comment by fadroid** [comment]
Thanks for assistance and this project! I got everything up and running and it's awesome!
