### ISSUE TITLE
No audio, button doesn't work, LED strip lights up red

### ISSUE THREAD

**Issue by Rememberthecreed** [Protonerd/FX-SaberOS#98]
I have a video on the FX-SaberOS facebook page showing my setup. After following SirRawThunderMan's tutorial on both editing the code and loading sound fonts on a micro SD, I loaded the card into the board, and powered it on. No boot sound, the tactile switch I'm using for the main switch isn't working, and the Neopixel Strip lights up all red. I pulled the recharge port off and plugged the battery into the board, and same issue. On video I got a "Diyino Jukebox" sound to come out of the speaker, but no lightsaber boot sound. 
Short of the base code, I only edited the Config_HW.h and Config_SW.h files (as it was in SirRawThunderMan's video). Maybe the goof up is there. All other config and .h files, I left as stock. 

Config_HW.h
`/*
 * Config_HW.h
 *
 * Created on: 30 March 2017
 * author:    Andras Kun (kun.andras@yahoo.de)
 * Source :  https://github.com/Protonerd/FX-SaberOS
 * This tab contains all settings necessary to define your saber board's electronic hardware configuration
 */

#if not defined CONFIG_HW_H_
#define CONFIG_HW_H_

/* Board definitions
 *  Define what kind of Arduino compatible board you have in your saber.
 *  DIYino Prime and Stardust are both dedicated, fully integrated
 *  saber boards manufactured by ProtoWerkstatt.
 *  For more information on DIYino products, see:
 *  https://github.com/Protonerd/DIYino
 *  https://www.facebook.com/ProtoWerkstatt-740015792832712/
 *  If you have a home-brew solution using the Arduino Nano, choose DIYINO_PRIME below
 */

#define DIYINO_PRIME // including home-brew
//#define DIYINO_STARDUST_V2
//#define DIYINO_STARDUST_V3

/***** BOARD PINOUT DEFINITIONS ******/

/*
 * Definition of the MAIN and AUX buttons of your saber.
 * These 2 buttons are used to interact with the saber electronics in the hilt
 * With the SINGLEBUTTON compile directive you can configure your saber electronics
 * to use only a single button to interact with your board.
 */

// If your saber has only a single button to interact with the electronics, uncomment the next line
// in case you have 2 buttons (referred to as main and aux buttons) leave this line commented out

#define SINGLEBUTTON
 
#ifdef DIYINO_PRIME 
  #define MAIN_BUTTON     12
  #ifndef SINGLEBUTTON
    #define AUX_BUTTON   4
  #endif
#else if defined DIYINO_STARDUST_V2 or defined DIYINO_STARDUST_V3
  #define MAIN_BUTTON      12
  #ifndef SINGLEBUTTON
    #define AUX_BUTTON   11 // 2
  #endif
#endif

/*
 * BLADE TYPE
 *
 * RGB LED OR PIXELBLADE users:
 * Comment the following line will
 * disable and remove all LEDSTRINGS
 * blocks from compile
 *************************************/
//#define LEDSTRINGS
//#define STAR_LED
#define PIXELBLADE
//#define ADF_PIXIE_BLADE

/************************************/
/*
 * SABER TYPE
 * currently in v1.3 only the CROSSGUARDSABER
 * will have any effect on the code
 * due to the fire blade effect
 *************************************/
#define SINGLEBLADE  // i.e. Graflex
//#define SABERSTAFF  // i.e. Darth Maul saber with dual blades
//#define CROSSGUARDSABER  // i.e. Kylo Ren saber

/*
 * POWER SAVING CIRCUITRY
 * Definition of the power switches (DIYino Prime v1.5 or greater, STARDUST
 * The MP3 power switch will cut power to the MP3 chipset as well as disable the audio amp
 * The FTDI power switch will cut power to the Serial-to-UART FTDI chipset, saving power and
 * allowing a PC to access the SD-card or SPI flash via the MP3 chipset over USB.
 * Enable DEEP_SLEEP in software config to make use of the power saving options.
 */
#ifdef DIYINO_PRIME 
  #define MP3_PSWITCH 15 // A1
  #define FTDI_PSWITCH 16 // A2
#else if defined DIYINO_STARDUST_V2 or defined DIYINO_STARDUST_V3 
  #define MP3_PSWITCH 17 // A3
  #define FTDI_PSWITCH 16 // A2
#endif
/*
 * General configuration for the main saber blade illumination types
 * STAR_LED refers to an in-hilt high-power LED module, usually of type RGB for color mixing, but can be a single LED type or any combination
 * of colors and LED dice up to 3 (more can be configured on demand, up to 6 with DIYino Prime
 * PIXELBLADE defines a neopixel stripe running the length of the blade. For more information on neopixels, see: https://www.adafruit.com/category/168
 * Currently supported chip set: WS2812B
 * LEDSTRINGS are commonly known as segmented LED strings and represent a blade type where thru-hole LEDs of a single color are connected in parallel
 * along the length of the blade. Currently supported number of segments: 6 (like Hasbro high-end and Plecter boards among others)
 */

  #ifdef DIYINO_PRIME 
    #define LED_RED       3
    #define LED_GREEN       5
    #define LED_BLUE      6
  #else if defined DIYINO_STARDUST_V2 or defined DIYINO_STARDUST_V3
    #define LED_RED       5
    #define LED_GREEN       6
    #define LED_BLUE      9
  #endif

#if I2CDEV_IMPLEMENTATION == I2CDEV_ARDUINO_WIRE
#include <Wire.h>
#endif

  #if defined LEDSTRINGS or defined STAR_LED
    #define NUMPIXELS 0
  #endif
  
  #ifdef PIXELBLADE
    // How many leds in one strip?
    #define NUMPIXELS 115  // can go up to 120, could lead to memory overflow if further increased, causing instability
    // For led chips like NEOPIXELs, which have a data line, ground, and power, you just
    // need to define DATA_PIN.
    #define DATA_PIN       13 // D13
  #endif

  #ifdef ADF_PIXIE_BLADE
    #define NUMPIXELS 1
    #define PIXIEPIN  13 // Pin number for SoftwareSerial output
  #endif
  

  
  #ifdef CROSSGUARDSABER
    // define how many pixels are used for the crossguard and how many for the main blade
    #define CROSSGUARD_LENGTH 10 // cross guard stripe length
    #define MAINBLADE_LENGTH 50 // main blade stripe length
    #define CROSSGUARD_OFFSET 0
    #define MAINBLADE_OFFSET 10
    #define STAGGERED_IGNITION_DELAY 1000
  #endif

  #ifdef DIYINO_PRIME
    #define LS1       3
    #define LS2       5
    #define LS3       6
    #define LS4       9
    #define LS5       10
    #define LS6       11
  #else if defined DIYINO_STARDUST_V2 or defined DIYINO_STARDUST_V3
    #define LS1       5
    #define LS2       6
    #define LS3      9
  #endif
  /*
   * FoCSTRING
   * Enable/disable management of
   * single Flash On Clash ledstring
   *************************************/
  //#define FoCSTRING      14

/*
 * BUTTON ACCENT_LED
 * Enable/disable management of
 * a button accent led
 *************************************/
#define HARD_ACCENT
#ifdef DIYINO_PRIME
  #ifdef HARD_ACCENT
    #define ACCENT_LED 14 //A0
  #endif
#else if defined DIYINO_STARDUST_V2 or defined DIYINO_STARDUST_V3
  #ifdef HARD_ACCENT
    #define ACCENT_LED 14 //A0 is an auxiliary pin on Stardust v2
  #endif
#endif
/*
 * MP3 chips YX5200 or YX6300 Tx and Rx ins, as well as the ADC pins connected to the SPK terminals for AudioTracker
 */
#define DFPLAYER_RX      8
#define DFPLAYER_TX     7
#define SPK1        20 //A6
#define SPK2        21 //A7

#define BATTERY_CHECK // comment to disable
#ifdef BATTERY_CHECK
  #ifdef DIYINO_PRIME
    #define BATTERY_READPIN 17 //A3 - read battery level
  #endif
  #if defined DIYINO_STARDUST_V2 or defined DIYINO_STARDUST_V3
    #define BATTERY_READPIN 15
  #endif
#endif

/*!!!!!IMPORTANT IMPORTANT IMPORTANT IMPORTANT IMPORTANT!!!
 *
 * MPU6050 device ORIENTATION
 * Choose which MPU's axis is parallel
 * to your blade axis
 *************************************/
//#define BLADE_X
#define BLADE_Y
//#define BLADE_Z
/************************************/

/*
 * MPU6050 calibrated offset values
 * If defined, calibration values will be retrieved from EEPROM
 * use this option if the MPU6050_calibration sketch wrote the calibrated offsets
 * into the EEPROM (default address is 96)
 * If not defined, you have to note down the calibrated offset values
 * and assign them to the respective variables in the code.
 *************************************/
#define MPUCALOFFSETEEPROM
#ifdef MPUCALOFFSETEEPROM
  #define MEMORYBASEMPUCALIBOFFSET 200 // 96 -> increased to 200 due to storing RGB PWM values in EEPROM takes a lot of space (3 x 1byte x 3 color types x nr of sound fonts i.e. for 5 sound fonts 45 bytes
#endif

#endif /* CONFIG_HW_H_ */`

Config_SW.h (I don't remember if I edited this part of the code at all, but it was in the youtube video, so I for sure was going through it)
`/*
 * Config_SW.h
 *
 * Created on: 30 March 2017
 * author:    Andras Kun (kun.andras@yahoo.de)
 * Source :  https://github.com/Protonerd/FX-SaberOS
 * This tab contains all settings necessary to define your saber board's electronic software configuration
 */

#include "Config_HW.h"

#if not defined CONFIG_SW_H_
#define CONFIG_SW_H_

/* INCLUDE_COMPILE_INFO will print the compile date and file location to the serial monitor at boot.
This is useful for keeping track of custom builds or which version has been installed.
It is important to note that this will take up some memory in proportion the the length of the file location/name */
//#define INCLUDE_COMPILE_INFO

/*
 * DEFAULT CONFIG PARAMETERS
 * Will be overriden by EEPROM settings
 * once the first save will be done
 *************************************/
// memory base in EEPROM for configuration variables, i.e. the config block will start at EEPROM address 32
#define MEMORYBASE       32
#define VOL          31
#define SOUNDFONT       3
#define SWING_THRESHOLD         1000
#define CLASH_THRESHOLD 10 // 10 was the original value in LSOS, Jason's value changed it to 6, but it resulted in false clash trigges at more forceful swings
/************************************/

#if defined LEDSTRINGS
  #define CONFIG_VERSION     "L01"
#endif
#if defined STAR_LED
  #define CONFIG_VERSION     "L02"
  static const uint8_t rgbFactor = 255;
#endif
#if defined PIXELBLADE
  #define CONFIG_VERSION     "L03"
  static const uint8_t rgbFactor = 255;
#endif
#if defined ADF_PIXIE_BLADE
  #define CONFIG_VERSION     "L05"
  static const uint8_t rgbFactor = 255;
#endif

/*
 * SOFTWARE SWITCHES FOR DFPLAYER CHISET
 *************************************/

#ifdef ADF_PIXIE_BLADE
  #define OLD_DPFPLAYER_LIB
  #include "Adafruit_Pixie.h"
  #include <SoftwareSerial.h>
#endif
/**********END of blade type hardware settings **************************/

/*
 * FX settings
 * With the following compile directives you can fine tune your saber effects like clash, swing, blaster deflect etc.
 */

/*
 * CLASH DETECTION METHOD
 * Clash can be detected by programming the mpu to trigger an interupt
 * on motion. If a motion interrupt is triggered, it can either be
 * detected by connecting the MPU's INT signal to D2 of the AVR (-> CLASH_DET_MPU_INT)
 * or by polling the INT_STATUS register via I2C and determining the value (-> CLASH_DET_MPU_POLL)
 * of bit 6
 */
#define CLASH_DET_MPU_INT
//#define CLASH_DET_MPU_POLL
 
/* FX DURATIONS AND SUPRESS TIMES
 *  effects cannot be retriggered for the duration
 *  of their respective suppress pareameters

 */
#define SWING_SUPPRESS     300
#define CLASH_SUPRESS     400  // do not modify below 400, otherwise interlocking clash sounds can occur
#define BLASTERBLOCK_SUPRESS     500

/*
 *  HUM_RELAUNCH will tell the state machine to relaunch
 *  hum sound after this time period elapses
 */
#define HUM_RELAUNCH     2000

/*
 * How long do the light effect last for the different FX's, choose to synchronize with the sound effect
 */
#define CLASH_FX_DURATION 250
#define BLASTER_FX_DURATION 150
#define SWING_FX_DURATION 400
// select if swing shall be triggered by change in blade orientation and rotation; otherwise swing is simply determined by blade acceleration
#define SWING_QUATERNION

/*
 * BUTTONS PARAMETERS
 ************************************/
#define CLICK        200 //5    // ms you need to press a button to be a click
#define PRESS_ACTION    600 //200  // ms you need to press a button to be a long press, in action mode
#define PRESS_CONFIG    600 //400  // ms you need to press a button to be a long press, in config mode
/************************************/

/********** END of FX Settings **************/

/* MAX_BRIGHTNESS
 *
 * Maximum output voltage to apply to LEDS
 * Default = 100 (39,2%) Max=255 Min=0(Off)
 *
 * WARNING ! A too high value may burn
 * your leds. Please make your maths !
 * BE VERY CAREFULL WITH THIS ONE OR 
 * YOU'LL BURN YOUR BLADE'S LED 
 ************************************/
#define MAX_BRIGHTNESS    230
#define FLICKERDEPTH 100

/* DEEP_SLEEP
 * If you want to enable/disable
 * deep sleep capabalities
 * Starting from v1.6, deep sleep can be entered from the config menu after the volume setting
 * If you a device with a CPU wich is not
 * an Atmega328 : COMMENT THIS
 *************************************/
#define DEEP_SLEEP
#if defined DEEP_SLEEP
  #define SLEEPYTIME      (1000UL * 60 * 2) //2 mins, after which the board will automatically go to sleep mode (to be implemented)
  #include <avr/sleep.h>
  #include <avr/power.h>
#endif  // DEEP_SLEEP

/* COLOR CHANGE OPTIONS
 *  If you want to use the advanced Gravity Color method developed for FX-SaberOS
 *  leave the GRAVITY_COLOR compile directive defined.
 *  If instead you would like to work with pre-set color profiles (15 different, pre-defined colors)
 *  comment out the line with GRAVITY_COLOR, which will define COLOR_PROFILE to be used.
 *************************************/
//#define GRAVITY_COLOR
#ifndef GRAVITY_COLOR
  #define COLOR_PROFILE
#endif

#define ANIBLADE
/*
 * Enable Jukebox, an integrated MP3/WAV player which can play songs/music files
 * stored in the jukebox folder on your storage media (SD-card or SPI flash).
 * Define the number of songs you have using the NR_JUKEBOXSONGS compile statement in Soundfont.h
 */
//#define JUKEBOX

/***** Battery meter settings *****/
const long InternalReferenceVoltage = 1062;  // Adjust this value to your board's specific internal BG voltage
// To calculate BATTERY_FACTOR use a multimeter: actual voltage / reported voltage * current BATTERY_FACTOR
// BATTERY_FACTOR will be about about 6.4-6.5 for "homebrew" builds
#define BATTERY_FACTOR 6.43 // Callibration value to compensate for component variation 
#define LOW_BATTERY 3.3 // low voltage for battery, a 5v Arduino or DIYino requires 3.3v 
#define FULL_BATTERY 4.15 // full voltage for battery, nominally 4.2 for a 3.7v battery
//cRGB C1;  //Low meter color
//cRGB C2;  //middle meter color
//cRGB C3;  //high meter color

/*
 * Accent LED can be used to illuminate a button with an in-built LED
 * The pin definition for the button LED can be found in hardware config tab
 */
/*
 * Pixel or Hard Accent
 */

//#define PIXEL_ACCENT
#ifndef PIXEL_ACCENT
  #define HARD_ACCENT
#endif

#ifdef PIXEL_ACCENT
  #define NUM_ACCENT_PIXELS 1
  #define PIXEL_ACCENT_DATA 14 //A0
  #define PIXEL_ACCENT_BRIGHTNESS 255
//  #define ACCENT_SWAP_RG //define if Red and Green are swapped from the color order of your blade (for example if one is 5mm bulb and other is 5050 SMD)
#endif  
/*
 * DEBUG PARAMETERS
 */
/* LS_INFO
 * For daily use I recommend you comment LS_INFO
 * When you plug your device to USB uncomment LS_INFO !
 */
#define LS_LOOPLENGHT
#define LS_SERIAL  //enable serial communication using Wire library
#if defined LS_SERIAL
//#define LS_FSM
#define LS_INFO
//#define LS_DEBUG
#endif

#if defined LS_DEBUG
//#define LS_BUTTON_DEBUG
//#define LS_MOTION_DEBUG
//#define LS_MOTION_HEAVY_DEBUG
//#define LS_RELAUNCH_DEBUG
//#define LS_DEBUG_SLEEP
#endif

#if defined LS_MOTION_DEBUG
//#define LS_SWING_DEBUG
//#define LS_SWING_HEAVY_DEBUG
//#define LS_CLASH_DEBUG
//#define LS_CLASH_HEAVY_DEBUG
#endif`

**Comment by Protonerd** [comment]
My first guess is that your switch is broken. Can you check this?

**Comment by Rememberthecreed** [comment]
I did. It was part of the issue, the other was that I didn’t bridge all three rgb leads. I’ve got it working, thank you.

**Comment by Protonerd** [comment]
Great, glad it works again!!!
